data:
  dir: /usr/local/dkv/data
  invalidIndex: false
  cache: true
  compress: false
server:
  mode: release
  port: :9091
  sequence: true
  redcon:
    port: :6381
logger:
  level: info
ms:
  role: 2