data:
  dir: /usr/local/dkv/data/m
  invalidIndex: false
  cache: true
  compress: false
server:
  mode: release
  port: :8090
  sequence: true
  redcon:
    port: :5380
logger:
  level: info
ms:
  role: 1
  m:
    port: :7380