data:
  dir: /usr/local/dkv/data
  invalidIndex: false
  cache: true
    size: 1073741824
  compress: false
server:
  mode: release
  port: 9090
  sequence: true
  redis:
    port: 6380
logger:
  level: info
  dir: /usr/local/dkv/log
ms:
  role: 0
