data:
  dir: /usr/local/dkv/data/m
  invalidIndex: false
  cache: true
    size: 1073741824
  compress: false
server:
  mode: release
  port: 8090
  sequence: true
  redis:
    port: 5380
logger:
  level: info
  dir: /usr/local/dkv/log/m
ms:
  role: 1
  m:
    port: 7380
