data:
  dir: /usr/local/dkv/data/s
  invalidIndex: false
  cache: true
    size: 1073741824
  compress: false
server:
  mode: release
  port: 8091
  sequence: true
  redis:
    port: 5381
logger:
  level: info
  dir: /usr/local/dkv/log/s
ms:
  role: 2
  s:
    addr: localhost:7380
