data:
  dir: /tmp/dkv/data
  invalidIndex: false
  cache:
    open: true
    size: 1073741824
  compress:
    open: false
server:
  mode: debug
  port: 9090
  sequence: true
  redis:
    port: 6380
logger:
  level: info
  dir: /tmp/dkv/log
ms:
  role: 0
